#!/bin/sh
set -u

SCRIPT_NAME="po0-wan-probe"
SCRIPT_VERSION="2026.08.30+build.4"
SCRIPT_RELEASE_DATE="2026-08-30"
# CHANGELOG_BEGIN
# - 跟随 PO0 发布批次对齐到 2026.08.30+build.4；WAN 探针无行为变化。
# CHANGELOG_END
CONFIG_NAME="po0_wan_probe"
CONFIG_SECTION="main"
DEFAULT_ALLOWED_SOURCE="192.168.88.2"
DEFAULT_IP_CHECK_URLS="https://ip9.com.cn/get,https://myip.ipip.net/json"
ALLOWED_SOURCES=""
ALLOWED_WANS=""
IP_CHECK_URLS="${DEFAULT_IP_CHECK_URLS}"
PROBE_ENABLED="1"
