#!/bin/sh
set -u

SCRIPT_NAME="po0-wan-probe"
SCRIPT_VERSION="2026.09.05+build.2"
SCRIPT_RELEASE_DATE="2026-09-05"
# CHANGELOG_BEGIN
# - CI 跨平台兼容性修复；本脚本功能沿用 2026.09.05+build.1。
# CHANGELOG_END
CONFIG_NAME="po0_wan_probe"
CONFIG_SECTION="main"
DEFAULT_ALLOWED_SOURCE="192.168.88.2"
DEFAULT_IP_CHECK_URLS="https://ip9.com.cn/get,https://myip.ipip.net/json"
ALLOWED_SOURCES=""
ALLOWED_WANS=""
IP_CHECK_URLS="${DEFAULT_IP_CHECK_URLS}"
PROBE_ENABLED="1"
