#!/usr/bin/env bash
set -uo pipefail

PO0_RELEASE_DOWNLOAD_BASE_URL="${PO0_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/SchweppesSoda/VPS-Toolkit/releases/latest/download}"
DOWNLOAD_URL="${PO0_OUTBOUND_IP_REPORT_DOWNLOAD_URL:-${PO0_SELF_REPORT_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/po0-outbound-ip-report.sh}}"
SCRIPT_NAME="po0-outbound-ip-report"
SCRIPT_VERSION="2026.07.01+build.5"
SCRIPT_RELEASE_DATE="2026-07-01"
# CHANGELOG_BEGIN
# - 新增 SSID 本地跳过上报配置：命中本机当前 SSID 时只在客户端本地记录跳过摘要，不上传 SSID，也不改变 LAN Worker / PO0 协议。
# - SSID 读取失败会继续正常上报；手动上报命中 SSID 跳过规则时会询问是否强制继续。
# CHANGELOG_END
MENU_RIGHT_COLUMN=46
PANEL_VALUE_COLUMN=24
ENV_WORKER_URL="${WORKER_URL-}"
ENV_SOURCE_ID="${SOURCE_ID-}"
ENV_IDENTITY="${IDENTITY-}"
ENV_ALLOW_HTTP="${ALLOW_HTTP-}"
ENV_IP_CHECK_URL="${IP_CHECK_URL-}"
ENV_IP_CHECK_URLS="${IP_CHECK_URLS-}"
ENV_INSTALL_PATH="${INSTALL_PATH-}"
ENV_MINUTES="${MINUTES-}"
ENV_INTERVAL_SECONDS="${INTERVAL_SECONDS-}"
CONFIG_FILE="${PO0_OUTBOUND_IP_REPORT_CONFIG:-${PO0_SELF_REPORT_CONFIG:-${SELF_REPORT_CONFIG:-}}}"
CONFIG_FILE_EXPLICIT="0"
[[ -n "${CONFIG_FILE}" ]] && CONFIG_FILE_EXPLICIT="1"
WORKER_URL=""
SOURCE_ID=""
IDENTITY=""
SOURCE_ID_EXPLICIT="0"
IDENTITY_EXPLICIT="0"
SECRET=""
ALLOW_HTTP=""
IP_CHECK_URL="https://ip9.com.cn/get"
IP_CHECK_URLS=""
INSTALL_PATH=""
INSTALL_PATH_EXPLICIT="0"
INSTALL_CRON=""
SHOW_MENU=""
SHOW_VERSION=""
SHOW_CHANGELOG=""
UPGRADE_SELF=""
SAVE_CONFIG=""
PAUSE_SCHEDULE=""
RESUME_SCHEDULE=""
SHOW_SCHEDULE_STATUS=""
SCHEDULE_PAUSED="0"
CRON_MINUTES="60"
MAX_CRON_MINUTES="10080"
INTERVAL_SECONDS=""
HAD_ARGS=0
[[ "$#" -gt 0 ]] && HAD_ARGS=1
