#!/usr/bin/env bash
set -uo pipefail

PO0_RELEASE_DOWNLOAD_BASE_URL="${PO0_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/SchweppesSoda/VPS-Toolkit/releases/latest/download}"
DOWNLOAD_URL="${PO0_OUTBOUND_IP_REPORT_DOWNLOAD_URL:-${PO0_SELF_REPORT_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/po0-outbound-ip-report.sh}}"
SCRIPT_NAME="po0-outbound-ip-report"
SCRIPT_VERSION="2026.09.05+build.6"
SCRIPT_RELEASE_DATE="2026-09-05"
# CHANGELOG_BEGIN
# - 旁路网关使用专用源地址直连探测真实 WAN IP，域名由主路由 DNS 解析；LAN Worker 提交遵循本机网络规则。
# CHANGELOG_END
MENU_RIGHT_COLUMN=46
PANEL_VALUE_COLUMN=24
ENV_WORKER_URL="${WORKER_URL-}"
ENV_WORKER_ENABLED="${WORKER_ENABLED-}"
ENV_FIREWALL_TOKENS="${PO0_FIREWALL_TOKENS-}"
ENV_FIREWALL_TOKENS_SET="0"
[[ -n "${PO0_FIREWALL_TOKENS+x}" ]] && ENV_FIREWALL_TOKENS_SET="1"
ENV_SOURCE_ID="${SOURCE_ID-}"
ENV_IDENTITY="${IDENTITY-}"
ENV_ALLOW_HTTP="${ALLOW_HTTP-}"
ENV_IP_CHECK_URL="${IP_CHECK_URL-}"
ENV_IP_CHECK_URLS="${IP_CHECK_URLS-}"
ENV_INSTALL_PATH="${INSTALL_PATH-}"
ENV_MINUTES="${MINUTES-}"
ENV_INTERVAL_SECONDS="${INTERVAL_SECONDS-}"
CONFIG_FILE="${PO0_OUTBOUND_IP_REPORT_CONFIG:-${PO0_SELF_REPORT_CONFIG:-${SELF_REPORT_CONFIG:-}}}"
CONFIG_FILE_EXPLICIT="0"
[[ -n "${CONFIG_FILE}" ]] && CONFIG_FILE_EXPLICIT="1"
WORKER_URL=""
WORKER_ENABLED=""
PO0_FIREWALL_TOKENS=""
SOURCE_ID=""
IDENTITY=""
SOURCE_ID_EXPLICIT="0"
IDENTITY_EXPLICIT="0"
SECRET=""
ALLOW_HTTP=""
IP_CHECK_URL="https://ip9.com.cn/get"
IP_CHECK_URLS=""
WANS=""
WANS_CLI_SEEN="0"
ROUTER_PROBE_URL=""
ROUTER_PROBE_BATCH_RAW=""
INSTALL_PATH=""
INSTALL_PATH_EXPLICIT="0"
INSTALL_CRON=""
SHOW_MENU=""
SHOW_VERSION=""
SHOW_CHANGELOG=""
UPGRADE_SELF=""
SAVE_CONFIG=""
PAUSE_SCHEDULE=""
RESUME_SCHEDULE=""
SHOW_SCHEDULE_STATUS=""
RUN_ONCE=""
SHOW_OFFICIAL_STATUS=""
CLEAR_OFFICIAL_TOKENS=""
SCHEDULED_RUN="0"
SCHEDULE_PAUSED="0"
CRON_MINUTES="60"
MAX_CRON_MINUTES="10080"
INTERVAL_SECONDS=""
HAD_ARGS=0
[[ "$#" -gt 0 ]] && HAD_ARGS=1

report_detail_enabled() {
    return 0
}
