#!/usr/bin/env bash
set -uo pipefail

PO0_RELEASE_DOWNLOAD_BASE_URL="${PO0_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/SchweppesSoda/VPS-Toolkit/releases/latest/download}"
DOWNLOAD_URL="${PO0_SELF_REPORT_MACOS_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/po0-outbound-ip-report-macos.sh}"
SCRIPT_NAME="po0-self-report-macos"
SCRIPT_VERSION="2026.06.25+build.12"
SCRIPT_RELEASE_DATE="2026-06-25"
# CHANGELOG_BEGIN
# - macOS Self-report 新增默认静默的通知开关、--notify / --no-notify 和菜单切换入口。
# CHANGELOG_END
MENU_RIGHT_COLUMN=46
PANEL_VALUE_COLUMN=24
ENV_WORKER_URL="${WORKER_URL-}"
ENV_SOURCE_ID="${SOURCE_ID-}"
ENV_IDENTITY="${IDENTITY-}"
ENV_ALLOW_HTTP="${ALLOW_HTTP-}"
ENV_IP_CHECK_URL="${IP_CHECK_URL-}"
ENV_IP_CHECK_URLS="${IP_CHECK_URLS-}"
ENV_INSTALL_PATH="${INSTALL_PATH-}"
ENV_MINUTES="${MINUTES-}"
ENV_INTERVAL_SECONDS="${INTERVAL_SECONDS-}"
ENV_NOTIFY="${NOTIFY-}"
CONFIG_FILE="${PO0_SELF_REPORT_CONFIG:-${SELF_REPORT_CONFIG:-}}"
WORKER_URL=""
SOURCE_ID=""
IDENTITY=""
SOURCE_ID_EXPLICIT="0"
IDENTITY_EXPLICIT="0"
SECRET=""
ALLOW_HTTP=""
IP_CHECK_URL="https://ip9.com.cn/get"
IP_CHECK_URLS=""
INSTALL_PATH=""
INSTALL_CRON=""
SHOW_MENU=""
SHOW_VERSION=""
SHOW_CHANGELOG=""
UPGRADE_SELF=""
SAVE_CONFIG=""
PAUSE_SCHEDULE=""
RESUME_SCHEDULE=""
SHOW_SCHEDULE_STATUS=""
SCHEDULE_PAUSED="0"
NOTIFY="0"
NOTIFY_ARG=""
CRON_MINUTES="60"
MAX_CRON_MINUTES="10080"
INTERVAL_SECONDS=""
HAD_ARGS=0
[[ "$#" -gt 0 ]] && HAD_ARGS=1
