#!/usr/bin/env bash
set -uo pipefail

PO0_RELEASE_DOWNLOAD_BASE_URL="${PO0_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/SchweppesSoda/VPS-Toolkit/releases/latest/download}"
DOWNLOAD_URL="${PO0_LAN_CLIENT_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/po0-lan-client.sh}"
MANAGER_DOWNLOAD_URL="${PO0_MANAGER_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/nftables-relay-manager.sh}"
SCRIPT_NAME="po0-lan-worker-client"
SCRIPT_VERSION="2026.09.08+build.1"
SCRIPT_RELEASE_DATE="2026-09-08"
RESOURCE_TOKEN="${PO0_RESOURCE_TOKEN:-}"
PO0_FIREWALL_TOKENS="${PO0_FIREWALL_TOKENS:-}"
CONFIG_FILE="${PO0_LAN_CLIENT_CONFIG:-}"
SETTINGS_FILE="${PO0_LAN_CLIENT_SETTINGS:-}"
INSTALL_PATH="${PO0_LAN_CLIENT_INSTALL_PATH:-}"
MANAGER_UPDATE_LISTEN="${PO0_MANAGER_UPDATE_LISTEN:-127.0.0.1:8789}"
MANAGER_UPDATE_DOMAIN="${PO0_MANAGER_UPDATE_DOMAIN:-}"
MANAGER_UPDATE_DEFAULT_PORT="${PO0_MANAGER_UPDATE_DEFAULT_PORT:-2333}"
MANAGER_UPDATE_BACKEND="${PO0_MANAGER_UPDATE_BACKEND:-127.0.0.1:8789}"
MANAGER_UPDATE_CADDY_SNIPPET="${PO0_MANAGER_UPDATE_CADDY_SNIPPET:-/etc/caddy/conf.d/po0-manager-update.caddy}"
CADDYFILE_PATH="${PO0_CADDYFILE:-/etc/caddy/Caddyfile}"
C_RESET=""
C_BOLD=""
C_DIM=""
C_GREEN=""
C_YELLOW=""
C_RED=""
C_CYAN=""
C_PANEL=""
# CHANGELOG_BEGIN
# - 精简为 PO0 更新服务；保留现有 HTTP 地址、服务和更新密钥。
# - 移除自建上报与资源队列；提供旧配置备份和官方客户端迁移入口。
# CHANGELOG_END
# Compatibility marker for old self-updaters: --resource-task-upload is retired.
UPDATE_KEYS_FILE=""
