#!/usr/bin/env bash
set -uo pipefail

SCRIPT_NAME="po0-nftables-relay-manager"
SCRIPT_VERSION="2026.09.08+build.1"
SCRIPT_RELEASE_DATE="2026-09-08"
# CHANGELOG_BEGIN
# - 精简为转发管理；保留 Worker 鉴权更新、备份恢复和旧配置迁移检查。
# - 退役自建白名单、接收与资源任务；不接管系统入站防火墙。
# CHANGELOG_END
CONF_DIR="${PO0_CONF_DIR:-/etc/nftables.d}"
MAIN_CONF="${PO0_MAIN_CONF:-/etc/nftables.conf}"
NFT_CONF="${CONF_DIR}/po0-relay.conf"
SETTINGS_FILE="${CONF_DIR}/po0-relay.env"
RULES_FILE="${CONF_DIR}/po0-relay.rules"
BACKUP_DIR="${CONF_DIR}/backups"
EXPORT_DIR="${BACKUP_DIR}/exports"
SYSCTL_CONF="${PO0_SYSCTL_CONF:-/etc/sysctl.d/99-po0-relay.conf}"
# Existing update pairings retain this historical filename.
UPDATE_TOKEN_FILE="${CONF_DIR}/po0-relay-resource-task.token"
MANAGER_INSTALL_PATH="${PO0_MANAGER_INSTALL_PATH:-/root/nftables-relay-manager.sh}"
PO0_RELEASE_DOWNLOAD_BASE_URL="${PO0_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/SchweppesSoda/VPS-Toolkit/releases/latest/download}"
MANAGER_DOWNLOAD_URL="${PO0_MANAGER_DOWNLOAD_URL:-${PO0_RELEASE_DOWNLOAD_BASE_URL}/nftables-relay-manager.sh}"
NAT_TABLE="po0_relay_nat"
MANGLE_TABLE="po0_relay_mangle"
BLOCKED_LISTEN_PORTS="22 80 443 8080 8443 8000 1080"
FORWARD_PORT_MIN="24576"
FORWARD_PORT_MAX="49151"
FORWARD_PORT_RANDOM_TRIES="200"

RELAY_MODE="mixed"
NODE_NAME=""
RELAY_LAN_IP=""
ENABLE_MSS_CLAMP="1"
MSS_VALUE="1452"
MANAGE_INPUT_FIREWALL="0"
SSH_PORTS=""
ENABLE_SRC_ALLOWLIST="0"
MANAGER_UPDATE_URL=""
declare -a RULES=()
declare -a IMPORTED_RULES=()
declare -a DISCOVERED_RULES=()

C_RESET=""
C_BOLD=""
C_DIM=""
C_GREEN=""
C_YELLOW=""
C_RED=""
C_CYAN=""
C_PANEL=""

RULE_ID=""
RULE_NAME=""
RULE_PROTO=""
RULE_LPORT=""
RULE_DIP=""
RULE_DPORT=""
RULE_ENABLED=""
RULE_SNAT_MODE=""
PARSED_RULE=""
RULE_TOTAL=0
RULE_ENABLED_COUNT=0
RULE_DISABLED_COUNT=0
TEMPLATE_OUTPUT_PATH=""
RELAY_LAN_IP_SOURCE="none"
RULES_SOURCE="none"
DISCOVERED_RULES_SOURCE="none"
PUBLIC_IP=""
PUBLIC_IP_SOURCE="none"
PUBLIC_IP_CACHE=""
PUBLIC_IP_CACHE_SOURCE="none"
PUBLIC_IP_PROBE_DONE="0"
SETTINGS_CACHE_READY="0"
RULES_CACHE_READY="0"
DISCOVERY_CACHE_READY="0"
DISCOVERED_RULE_COUNT=0
declare -a TEMP_FILES=()
TEMP_FILE_RESULT=""
declare -a TEMP_DIRS=()
TEMP_DIR_RESULT=""
